config/routes.rb
Rails.application.routes.draw do
  namespace :dashboards, path: 'dashboard' do
    resources :companies do
      resources :vacancies do
        put :archive, on: :member
        put :unarchive, on: :member
      end
    end
    resources :resumes do
      put :archive, on: :member
      put :unarchive, on: :member
    end
  end
  resource :dashboard
  resources :vacancies

  resources :resumes
  devise_for :users
  root to: 'pages#home'
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :vacancies
end

app/controllers/dashboards/companies_controller.rb
module Dashboards
  class CompaniesController < DashboardsController
    before_action :authenticate_user!
    before_action :set_company, only: [:show, :edit, :update, :destroy]
    before_action :set_user_companies

    def index
      @companies = current_user.companies
    end

    def show
      @vacancies = @company
                    .vacancies
                    .published
                    .paginate(page: params[:page], per_page: 10)
      @archived_vacancies = @company
                              .vacancies
                              .archived
                              .paginate(page: params[:page], per_page: 10)
    end

    def new
      @company = current_user.companies.build
    end

    def edit
    end

    def create
      @company = current_user.companies.build(company_params)

      if @company.save
        redirect_to dashboards_companies_path, notice: 'Company was created.'
      else
        render :new
      end
    end

    def update
      if @company.update(company_params)
        redirect_to dashboards_companies_path, notice: 'Company was updated.'
      else
        render :edit
      end
    end

    def destroy
      @company.destroy

      redirect_to dashboards_companies_path, notice: 'Company was destroyed.'
    end

    private

    def set_company
      @company = Company.find(params[:id])
    end

    def set_user_companies
      @companies = current_user.companies
    end

    def company_params
      params.require(:company).permit(:title, :about, :url)
    end
  end
end

app/controllers/dashboards/resumes_controller.rb
module Dashboards
  class ResumesController < DashboardsController
    before_action :authenticate_user!
    before_action :set_resume, only: [
      :show, :edit, :update, :destroy, :archive, :unarchive
    ]
    before_action :set_user_companies

    def index
      @resumes = current_user
                  .resumes
                  .published
                  .ordered
                  .paginate(page: params[:page], per_page: 10)
      @archived_resumes = current_user
                            .resumes
                            .archived
                            .paginate(page: params[:page], per_page: 10)
    end

    def show
    end

    def new
      @resume = Resume.new
    end

    def edit
      authorize @resume
    end

    def create
      @resume = current_user.resumes.build(resume_params)

      if @resume.save
        redirect_to [:dashboards, @resume], notice: 'Resume was created.'
      else
        render :new
      end
    end

    def update
      authorize @resume

      if @resume.update(resume_params)
        redirect_to [:dashboards, @resume], notice: 'Resume was updated.'
      else
        render :edit
      end
    end

    def destroy
      authorize @resume

      @resume.destroy

      redirect_to dashboard_path, notice: 'Resume was destroyed.'
    end

    def archive
      @resume.archive!

      redirect_to [:dashboards, :resumes], notice: 'Resume was archived'
    end

    def unarchive
      @resume.unarchive!

      redirect_to [:dashboards, :resumes], notice: 'Resume was unarchived'
    end

    private

    def set_resume
      @resume = Resume.find(params[:id])
    end

    def set_user_companies
      @companies = current_user.companies
    end

    def resume_params
      params.require(:resume).permit(
        :title, :courses, :books, :projects, :archived, :experience, :skills,
        :remote, :relocate, :category_id, :salary_from, :salary_to, :currency
      )
    end
  end
end

app/controllers/dashboards/vacancies_controller.rb
module Dashboards
  class VacanciesController < DashboardsController
    before_action :set_company
    before_action :set_vacancy, only: [
      :show, :edit, :update, :destroy, :archive, :unarchive
    ]

    def show
    end

    def new
      @vacancy = Vacancy.new
    end

    def edit
    end

    def create
      @vacancy = @company.vacancies.build(vacancy_params)

      if @vacancy.save
        redirect_to [:dashboards, @company], notice: 'Vacancy was created.'
      else
        render :new
      end
    end

    def update
      if @vacancy.update(vacancy_params)
        redirect_to [:dashboards, @company], notice: 'Vacancy was updated.'
      else
        render :edit
      end
    end

    def destroy
      @vacancy.destroy

      redirect_to dashboard_path, notice: 'Vacancy was destroyed.'
    end

    def archive
      @vacancy.archive!

      redirect_to [:dashboards, @company], notice: 'Vacancy was archived'
    end

    def unarchive
      @vacancy.unarchive!

      redirect_to [:dashboards, @company], notice: 'Vacancy was unarchived'
    end

    private

    def set_vacancy
      @vacancy = Vacancy.find(params[:id])
    end

    def set_company
      @company = Company.find(params[:company_id])
    end

    def vacancy_params
      params.require(:vacancy).permit(
        :title, :salary_from, :about, :city, :remote, :relocate, :category_id
      )
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  layout 'dashboard'

  def show
    @resumes = current_user.resumes
    @companies = current_user.companies
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboards/companies/_form.html.slim
.col-md-8.col-md-offset-2
  = form_for [:dashboard, @company] do |f|
    - if @company.errors.any?
      #error_explanation
        h2 = "#{pluralize(@company.errors.count, "error")} prohibited this company from being saved:"
        ul
          - @company.errors.full_messages.each do |message|
            li = message

    .form-group
      = f.label :title
      = f.text_field :title, class: 'form-control'
    .form-group
      = f.label :about
      = f.text_area :about, class: 'form-control'
    .form-group
      = f.label :url
      = f.text_field :url, class: 'form-control'
    .actions = f.submit 'Save', class: 'btn btn-default'

app/views/dashboards/companies/edit.html.slim
h1 Editing company

== render 'form'

= link_to 'Show', @company
'|
= link_to 'Back', companies_path

app/views/dashboards/companies/index.html.slim
h1 Listing companies

table.table.table-bordered.table-hover
  thead
    tr
      th Title
      th

  tbody
    - @companies.each do |company|
      tr
        td = link_to company.title, [:dashboard, company]
        td
          => link_to 'Edit', edit_dashboard_company_path(company)
          = link_to 'Destroy', [:dashboard, company], data: { confirm: 'Are you sure?' }, method: :delete

app/views/dashboards/companies/new.html.slim
h1 New company

== render 'form'

app/views/dashboards/companies/show.html.slim
h1 = @company.title
small = link_to 'Edit', [:edit, :dashboards, @company]

p = @company.about
p = @company.url

h1 Vacancies

.text-center = will_paginate @vacancies

table#published_vacancies.table.table-bordered.table-hover
  tr
    th Title
    th Actions

  - @vacancies.each do |vacancy|
    tr
      td = link_to vacancy.title, [:edit, :dashboards, @company, vacancy]
      td
        => link_to 'Delete', [:dashboards, @company, vacancy], method: :delete, data: { confirm: 'Are you sure?' }
        = link_to 'Archive', archive_dashboards_company_vacancy_path(@company, vacancy), method: :put

= link_to 'New vacancy', new_dashboards_company_vacancy_path(@company), class: 'btn btn-default'

.text-center = will_paginate @vacancies

h1 Archived vacancies

.text-center = will_paginate @archived_vacancies

table#archived_vacancies.table.table-bordered.table-hover
  tr
    th Title
    th Actions

  - @archived_vacancies.each do |vacancy|
    tr
      td = link_to vacancy.title, [:edit, :dashboards, @company, vacancy]
      td
        => link_to 'Delete', [:dashboards, @company, vacancy], method: :delete, data: { confirm: 'Are you sure?' }
        = link_to 'Unarchive', unarchive_dashboards_company_vacancy_path(@company, vacancy), method: :put

.text-center = will_paginate @archived_vacancies