config/routes.rb
Rails.application.routes.draw do
  namespace :dashboards, path: 'dashboard' do
    resources :companies do
      resources :vacancies do
        put :archive, on: :member
        put :unarchive, on: :member
      end
    end
    resources :resumes do
      put :archive, on: :member
      put :unarchive, on: :member
    end
  end
  resource :dashboard
  resources :vacancies

  resources :resumes
  devise_for :users
  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :resumes
  has_many :vacancies
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :vacancies
end

app/models/concerns/archivable.rb
module Archivable
  extend ActiveSupport::Concern
  included do
    def archive!
      update(archived: true)
    end

    def unarchive!
      update(archived: false)
    end
  end
end

app/models/concerns/scopable.rb
module Scopable
  extend ActiveSupport::Concern
  included do
    scope :ordered, -> { order(created_at: :desc) }
    scope :archived, -> { where(archived: true) }
    scope :published, -> { where(archived: false) }
  end
end

app/models/resume.rb
# == Schema Information
#
# Table name: resumes
#
#  id          :integer          not null, primary key
#  title       :string           default(""), not null
#  courses     :text
#  books       :text
#  projects    :text
#  published   :boolean          default(FALSE)
#  archived    :boolean          default(FALSE)
#  salary      :integer
#  experience  :text
#  skills      :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#  currency    :integer
#  salary_from :integer          default(0), not null
#  salary_to   :integer          default(0), not null
#

class Resume < ApplicationRecord
  include Scopable
  include Archivable
  belongs_to :user
  belongs_to :category

  validates :title, presence: true

  enum currency: [:rub, :usd, :eur]
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string           default(""), not null
#  surname                :string           default(""), not null
#  about                  :text
#  github                 :string
#  twitter                :string
#  city                   :string
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :resumes
  has_many :companies
end

app/models/vacancy.rb
class Vacancy < ApplicationRecord
  include Scopable
  include Archivable
  belongs_to :company
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :account_update,
      keys: [
        :name, :surname, :about, :github, :twitter, :city
      ]
    )
  end

  private

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to(request.referer || root_path)
  end
end

app/controllers/dashboards/resumes_controller.rb
module Dashboards
  class ResumesController < DashboardsController
    before_action :authenticate_user!
    before_action :set_resume, only: [
      :show, :edit, :update, :destroy, :archive, :unarchive
    ]
    before_action :set_user_companies

    def index
      @resumes = current_user
                  .resumes
                  .published
                  .ordered
                  .paginate(page: params[:page], per_page: 10)
      @archived_resumes = current_user
                            .resumes
                            .archived
                            .paginate(page: params[:page], per_page: 10)
    end

    def show
    end

    def new
      @resume = Resume.new
    end

    def edit
      authorize @resume
    end

    def create
      @resume = current_user.resumes.build(resume_params)

      if @resume.save
        redirect_to [:dashboards, @resume], notice: 'Resume was created.'
      else
        render :new
      end
    end

    def update
      authorize @resume

      if @resume.update(resume_params)
        redirect_to [:dashboards, @resume], notice: 'Resume was updated.'
      else
        render :edit
      end
    end

    def destroy
      authorize @resume

      @resume.destroy

      redirect_to dashboard_path, notice: 'Resume was destroyed.'
    end

    def archive
      @resume.archive!

      redirect_to [:dashboards, :resumes], notice: 'Resume was archived'
    end

    def unarchive
      @resume.unarchive!

      redirect_to [:dashboards, :resumes], notice: 'Resume was unarchived'
    end

    private

    def set_resume
      @resume = Resume.find(params[:id])
    end

    def set_user_companies
      @companies = current_user.companies
    end

    def resume_params
      params.require(:resume).permit(
        :title, :courses, :books, :projects, :archived, :experience, :skills,
        :remote, :relocate, :category_id, :salary_from, :salary_to, :currency
      )
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  layout 'dashboard'

  def show
    @resumes = current_user.resumes
    @companies = current_user.companies
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :set_resume, only: :show

  def index
    @resumes = Resume.published
                     .ordered
                     .paginate(page: params[:page], per_page: 10)
  end

  def show
    authorize @resume, :published?
  end

  private

  def set_resume
    @resume = Resume.find(params[:id])
  end

  def resume_params
    params.require(:resume).permit(
      :title, :courses, :books, :projects, :archived, :salary,
      :experience, :skills, :remote, :relocate
    )
  end
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  before_action :set_vacancy, only: :show

  def index
    @vacancies = Vacancy.ordered.paginate(page: params[:page], per_page: 15)
  end

  def show
  end

  private

  def set_vacancy
    @vacancy = Vacancy.find(params[:id])
  end

  def vacancy_params
    params.fetch(:vacancy, {})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_class_for(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hirejunior</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
    <%= render partial: "shared/flash", flash: flash %>
    <%= switch_user_select if Rails.env.development? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hirejunior</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <div class="container">
      <%= render 'dashboards/subnavbar' %>
      <%= render partial: "shared/flash", flash: flash %>
      <%= yield %>
      <%= switch_user_select if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/pages/home.html.slim
h1 Hire Junior!

.jumbotron
  .h4
    p Here you can hire junior or create resume to let companies, willing to hire juniors, find you!
    p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore veritatis placeat alias necessitatibus corrupti maxime suscipit inventore id ullam nam a iste earum, ipsam, voluptate, magnam? Magni tenetur ab laborum!

.text-center
  p.h3
    ' You can
    => link_to 'Search resumes', resumes_path
    ' or
    = link_to 'create one for yourself!', new_resume_path

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= alert_class_for(type) %> alert-dismissible fade in">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_navbar.slim
nav.navbar.navbar-default
  .container
    .navbar-header
      button { class = 'navbar-toggle collapsed'
               type = 'button'
               data-toggle = 'collapse'
               data-target = '#navbar-collapse'
               aria-expanded = 'false'
             }
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Hire Junior', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse id='navbar-collapse'
      ul.nav.navbar-nav
        li = link_to 'Resumes', resumes_path
        li = link_to 'Vacancies', vacancies_path
      ul.nav.navbar-nav.navbar-right
        - if signed_in?
          li = link_to 'Создать резюме', new_dashboards_resume_path
          li.dropdown
            a.dropdown-toggle href='#' data-toggle='dropdown'
              i.glyphicon.glyphicon-th-large
              span.caret
            ul.dropdown-menu role='menu'
              li = link_to 'Дашборд', dashboard_path
              li = link_to 'Настройки', edit_user_registration_path
              li = link_to 'Выход', destroy_user_session_path, data: { method: :delete }
        - else
          li.dropdown
            a.dropdown-toggle href='#' data-toggle='dropdown'
              i.glyphicon.glyphicon-lock
              span.caret
            ul.dropdown-menu role='menu'
              li = link_to 'Вход', new_user_session_path
              li = link_to 'Регистрация', new_user_registration_path