config/routes.rb
Rails.application.routes.draw do
  namespace :dashboards, path: 'dashboard' do
    resources :companies do
      resources :vacancies do
        put :archive, on: :member
        put :unarchive, on: :member
      end
    end
    resources :resumes do
      put :archive, on: :member
      put :unarchive, on: :member
    end
  end
  resource :dashboard
  resources :vacancies

  resources :resumes
  devise_for :users
  root to: 'pages#home'
end

app/models/resume.rb
# == Schema Information
#
# Table name: resumes
#
#  id          :integer          not null, primary key
#  title       :string           default(""), not null
#  courses     :text
#  books       :text
#  projects    :text
#  published   :boolean          default(FALSE)
#  archived    :boolean          default(FALSE)
#  salary      :integer
#  experience  :text
#  skills      :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#  currency    :integer
#  salary_from :integer          default(0), not null
#  salary_to   :integer          default(0), not null
#

class Resume < ApplicationRecord
  include Scopable
  include Archivable
  belongs_to :user
  belongs_to :category

  validates :title, presence: true

  enum currency: [:rub, :usd, :eur]
end

app/controllers/dashboards/companies_controller.rb
module Dashboards
  class CompaniesController < DashboardsController
    before_action :authenticate_user!
    before_action :set_company, only: [:show, :edit, :update, :destroy]
    before_action :set_user_companies

    def index
      @companies = current_user.companies
    end

    def show
      @vacancies = @company
                    .vacancies
                    .published
                    .paginate(page: params[:page], per_page: 10)
      @archived_vacancies = @company
                              .vacancies
                              .archived
                              .paginate(page: params[:page], per_page: 10)
    end

    def new
      @company = current_user.companies.build
    end

    def edit
    end

    def create
      @company = current_user.companies.build(company_params)

      if @company.save
        redirect_to dashboards_companies_path, notice: 'Company was created.'
      else
        render :new
      end
    end

    def update
      if @company.update(company_params)
        redirect_to dashboards_companies_path, notice: 'Company was updated.'
      else
        render :edit
      end
    end

    def destroy
      @company.destroy

      redirect_to dashboards_companies_path, notice: 'Company was destroyed.'
    end

    private

    def set_company
      @company = Company.find(params[:id])
    end

    def set_user_companies
      @companies = current_user.companies
    end

    def company_params
      params.require(:company).permit(:title, :about, :url)
    end
  end
end

app/controllers/dashboards/resumes_controller.rb
module Dashboards
  class ResumesController < DashboardsController
    before_action :authenticate_user!
    before_action :set_resume, only: [
      :show, :edit, :update, :destroy, :archive, :unarchive
    ]
    before_action :set_user_companies

    def index
      @resumes = current_user
                  .resumes
                  .published
                  .ordered
                  .paginate(page: params[:page], per_page: 10)
      @archived_resumes = current_user
                            .resumes
                            .archived
                            .paginate(page: params[:page], per_page: 10)
    end

    def show
    end

    def new
      @resume = Resume.new
    end

    def edit
      authorize @resume
    end

    def create
      @resume = current_user.resumes.build(resume_params)

      if @resume.save
        redirect_to [:dashboards, @resume], notice: 'Resume was created.'
      else
        render :new
      end
    end

    def update
      authorize @resume

      if @resume.update(resume_params)
        redirect_to [:dashboards, @resume], notice: 'Resume was updated.'
      else
        render :edit
      end
    end

    def destroy
      authorize @resume

      @resume.destroy

      redirect_to dashboard_path, notice: 'Resume was destroyed.'
    end

    def archive
      @resume.archive!

      redirect_to [:dashboards, :resumes], notice: 'Resume was archived'
    end

    def unarchive
      @resume.unarchive!

      redirect_to [:dashboards, :resumes], notice: 'Resume was unarchived'
    end

    private

    def set_resume
      @resume = Resume.find(params[:id])
    end

    def set_user_companies
      @companies = current_user.companies
    end

    def resume_params
      params.require(:resume).permit(
        :title, :courses, :books, :projects, :archived, :experience, :skills,
        :remote, :relocate, :category_id, :salary_from, :salary_to, :currency
      )
    end
  end
end

app/controllers/dashboards/vacancies_controller.rb
module Dashboards
  class VacanciesController < DashboardsController
    before_action :set_company
    before_action :set_vacancy, only: [
      :show, :edit, :update, :destroy, :archive, :unarchive
    ]

    def show
    end

    def new
      @vacancy = Vacancy.new
    end

    def edit
    end

    def create
      @vacancy = @company.vacancies.build(vacancy_params)

      if @vacancy.save
        redirect_to [:dashboards, @company], notice: 'Vacancy was created.'
      else
        render :new
      end
    end

    def update
      if @vacancy.update(vacancy_params)
        redirect_to [:dashboards, @company], notice: 'Vacancy was updated.'
      else
        render :edit
      end
    end

    def destroy
      @vacancy.destroy

      redirect_to dashboard_path, notice: 'Vacancy was destroyed.'
    end

    def archive
      @vacancy.archive!

      redirect_to [:dashboards, @company], notice: 'Vacancy was archived'
    end

    def unarchive
      @vacancy.unarchive!

      redirect_to [:dashboards, @company], notice: 'Vacancy was unarchived'
    end

    private

    def set_vacancy
      @vacancy = Vacancy.find(params[:id])
    end

    def set_company
      @company = Company.find(params[:company_id])
    end

    def vacancy_params
      params.require(:vacancy).permit(
        :title, :salary_from, :about, :city, :remote, :relocate, :category_id
      )
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  layout 'dashboard'

  def show
    @resumes = current_user.resumes
    @companies = current_user.companies
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :set_resume, only: :show

  def index
    @resumes = Resume.published
                     .ordered
                     .paginate(page: params[:page], per_page: 10)
  end

  def show
    authorize @resume, :published?
  end

  private

  def set_resume
    @resume = Resume.find(params[:id])
  end

  def resume_params
    params.require(:resume).permit(
      :title, :courses, :books, :projects, :archived, :salary,
      :experience, :skills, :remote, :relocate
    )
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/dashboards/resumes/_form.html.slim
.col-md-8.col-md-offset-2
  = form_for [:dashboards, @resume] do |f|
    - if @resume.errors.any?
      #error_explanation
        h2 = "#{pluralize(@resume.errors.count, "error")} prohibited this resume from being saved:"
        ul
          - @resume.errors.full_messages.each do |message|
            li = message

    .form-group
      = f.label :title, 'Должность'
      = f.text_field :title, class: 'form-control'
    .form-inline
      .form-group
        label
          | Желаемая оплата
          br
          ' От
          => f.number_field :salary_from, class: 'form-control'
          ' до
          => f.number_field :salary_to, class: 'form-control'
          = f.select :currency, Resume.currencies.keys.to_a, {}, { class: 'form-control' }
    .form-group
      label>
        | Готов к переезду?
        = f.check_box :relocate, class: 'form-control'
      label
        | Готов к удаленной работе?
        = f.check_box :remote, class: 'form-control'

    .form-group
      = f.select :category_id, Category.all.collect { |c| [c.title, c.id] }, {}, { class: 'form-control' }

    .form-group
      = f.label :experience, 'Опишите свой опыт в вашей сфере'
      = f.text_area :experience, class: 'form-control'
    .form-group
      = f.label :skills, 'Список навыков'
      = f.text_area :skills, class: 'form-control'
    .form-group
      = f.label :courses, 'Пройденные курсы'
      = f.text_area :courses, class: 'form-control'
    .form-group
      = f.label :books, 'Прочтенные книги'
      = f.text_area :books, class: 'form-control'
    .form-group
      = f.label :projects, 'Реализованные проекты'
      = f.text_area :projects, class: 'form-control'
    .actions = f.submit 'Опубликовать', class: 'btn btn-default'

app/views/dashboards/resumes/edit.html.slim
h1 Editing resume

== render 'form'

app/views/dashboards/resumes/index.html.slim
h1 Your resumes

table#published_resumes.table.table-bordered.table-hover
  tr
    th Title
    th Actions

  - @resumes.each do |resume|
    tr id=("resume-#{resume.id}")
      td = link_to resume.title, edit_dashboards_resume_path(resume)
      td
        = link_to 'Delete', dashboards_resume_path(resume), method: :delete, data: { confirm: 'Are you sure?' }
        = link_to 'Archive', archive_dashboards_resume_path(resume), method: :put

  .text-center
    = will_paginate @resumes

h1 Archived resumes

table#archived_resumes.table.table-bordered.table-hover
  tr
    th Title
    th Actions

  - @archived_resumes.each do |resume|
    tr id=("resume-#{resume.id}")
      td = link_to resume.title, edit_dashboards_resume_path(resume)
      td
        = link_to 'Delete', dashboards_resume_path(resume), method: :delete, data: { confirm: 'Are you sure?' }
        = link_to 'Unarchive', unarchive_dashboards_resume_path(resume), method: :put

app/views/dashboards/resumes/new.html.slim
h1 Создание резюме

.col-md-6.col-md-offset-3
  = render 'form'

app/views/dashboards/resumes/show.html.slim
h1 = @resume.title

.panel.panel-default
  .panel-heading
    h2 = link_to @resume.title, @resume
    - if policy(@resume).edit?
      small = link_to 'Edit', edit_resume_path(@resume)
  .panel-body
    .row
      .col-md-2
        = image_tag(Faker::Avatar.image('my-own-slug', '150x150'))
      .col-md-8
        h4 Опыт работы
        p = @resume.experience

        h4 Пройденные курсы
        p = @resume.courses

        h4 Прочитанные книги
        p = @resume.books

        h4 Проекты
        p = @resume.projects
      .col-md-2
        h4 Ожидаемая зарплата
        = "$#{@resume.salary_from}-#{@resume.salary_to}"

  .panel-footer
    h3 Контакты
    li = @resume.user.github
    li = @resume.user.twitter
    li = @resume.user.email
    / li = @resume.user.phone