config/routes.rb
Rails.application.routes.draw do
  namespace :dashboards, path: 'dashboard' do
    resources :companies do
      resources :vacancies do
        put :archive, on: :member
        put :unarchive, on: :member
      end
    end
    resources :resumes do
      put :archive, on: :member
      put :unarchive, on: :member
    end
  end
  resource :dashboard
  resources :vacancies

  resources :resumes
  devise_for :users
  root to: 'pages#home'
end

app/models/vacancy.rb
class Vacancy < ApplicationRecord
  include Scopable
  include Archivable
  belongs_to :company
  belongs_to :category
end

app/controllers/dashboards/companies_controller.rb
module Dashboards
  class CompaniesController < DashboardsController
    before_action :authenticate_user!
    before_action :set_company, only: [:show, :edit, :update, :destroy]
    before_action :set_user_companies

    def index
      @companies = current_user.companies
    end

    def show
      @vacancies = @company
                    .vacancies
                    .published
                    .paginate(page: params[:page], per_page: 10)
      @archived_vacancies = @company
                              .vacancies
                              .archived
                              .paginate(page: params[:page], per_page: 10)
    end

    def new
      @company = current_user.companies.build
    end

    def edit
    end

    def create
      @company = current_user.companies.build(company_params)

      if @company.save
        redirect_to dashboards_companies_path, notice: 'Company was created.'
      else
        render :new
      end
    end

    def update
      if @company.update(company_params)
        redirect_to dashboards_companies_path, notice: 'Company was updated.'
      else
        render :edit
      end
    end

    def destroy
      @company.destroy

      redirect_to dashboards_companies_path, notice: 'Company was destroyed.'
    end

    private

    def set_company
      @company = Company.find(params[:id])
    end

    def set_user_companies
      @companies = current_user.companies
    end

    def company_params
      params.require(:company).permit(:title, :about, :url)
    end
  end
end

app/controllers/dashboards/resumes_controller.rb
module Dashboards
  class ResumesController < DashboardsController
    before_action :authenticate_user!
    before_action :set_resume, only: [
      :show, :edit, :update, :destroy, :archive, :unarchive
    ]
    before_action :set_user_companies

    def index
      @resumes = current_user
                  .resumes
                  .published
                  .ordered
                  .paginate(page: params[:page], per_page: 10)
      @archived_resumes = current_user
                            .resumes
                            .archived
                            .paginate(page: params[:page], per_page: 10)
    end

    def show
    end

    def new
      @resume = Resume.new
    end

    def edit
      authorize @resume
    end

    def create
      @resume = current_user.resumes.build(resume_params)

      if @resume.save
        redirect_to [:dashboards, @resume], notice: 'Resume was created.'
      else
        render :new
      end
    end

    def update
      authorize @resume

      if @resume.update(resume_params)
        redirect_to [:dashboards, @resume], notice: 'Resume was updated.'
      else
        render :edit
      end
    end

    def destroy
      authorize @resume

      @resume.destroy

      redirect_to dashboard_path, notice: 'Resume was destroyed.'
    end

    def archive
      @resume.archive!

      redirect_to [:dashboards, :resumes], notice: 'Resume was archived'
    end

    def unarchive
      @resume.unarchive!

      redirect_to [:dashboards, :resumes], notice: 'Resume was unarchived'
    end

    private

    def set_resume
      @resume = Resume.find(params[:id])
    end

    def set_user_companies
      @companies = current_user.companies
    end

    def resume_params
      params.require(:resume).permit(
        :title, :courses, :books, :projects, :archived, :experience, :skills,
        :remote, :relocate, :category_id, :salary_from, :salary_to, :currency
      )
    end
  end
end

app/controllers/dashboards/vacancies_controller.rb
module Dashboards
  class VacanciesController < DashboardsController
    before_action :set_company
    before_action :set_vacancy, only: [
      :show, :edit, :update, :destroy, :archive, :unarchive
    ]

    def show
    end

    def new
      @vacancy = Vacancy.new
    end

    def edit
    end

    def create
      @vacancy = @company.vacancies.build(vacancy_params)

      if @vacancy.save
        redirect_to [:dashboards, @company], notice: 'Vacancy was created.'
      else
        render :new
      end
    end

    def update
      if @vacancy.update(vacancy_params)
        redirect_to [:dashboards, @company], notice: 'Vacancy was updated.'
      else
        render :edit
      end
    end

    def destroy
      @vacancy.destroy

      redirect_to dashboard_path, notice: 'Vacancy was destroyed.'
    end

    def archive
      @vacancy.archive!

      redirect_to [:dashboards, @company], notice: 'Vacancy was archived'
    end

    def unarchive
      @vacancy.unarchive!

      redirect_to [:dashboards, @company], notice: 'Vacancy was unarchived'
    end

    private

    def set_vacancy
      @vacancy = Vacancy.find(params[:id])
    end

    def set_company
      @company = Company.find(params[:company_id])
    end

    def vacancy_params
      params.require(:vacancy).permit(
        :title, :salary_from, :about, :city, :remote, :relocate, :category_id
      )
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  layout 'dashboard'

  def show
    @resumes = current_user.resumes
    @companies = current_user.companies
  end
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  before_action :set_vacancy, only: :show

  def index
    @vacancies = Vacancy.ordered.paginate(page: params[:page], per_page: 15)
  end

  def show
  end

  private

  def set_vacancy
    @vacancy = Vacancy.find(params[:id])
  end

  def vacancy_params
    params.fetch(:vacancy, {})
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
end

app/views/dashboards/vacancies/_form.html.slim
.col-md-8.col-md-offset-2
  = form_for dashboards_company_vacancies_path(@company) do |f|
    - if @vacancy.errors.any?
      #error_explanation
        h2 = "#{pluralize(@vacancy.errors.count, "error")} prohibited this vacancy from being saved:"
        ul
          - @vacancy.errors.full_messages.each do |message|
            li = message

    .form-group
      = f.label :title
      = f.text_field :title, class: 'form-control'
    .form-group
      = f.select :category_id, Category.all.collect { |c| [c.title, c.id] }, {}, { class: 'form-control' }
    .form-group
      = f.label :salary_from
      = f.number_field :salary_from, class: 'form-control'
    .form-group
      = f.label :about
      = f.text_area :about, class: 'form-control'
    .form-group
      = f.label :city
      = f.text_field :city, class: 'form-control'
    .form-group
      label>
        ' Remote?
        => f.check_box :remote, class: 'form-control'
      label>
        ' Relocate?
        = f.check_box :relocate, class: 'form-control'
    .actions = f.submit 'Publish', class: 'btn btn-default'

app/views/dashboards/vacancies/edit.html.slim
h1 Editing vacancy

== render 'form'

app/views/dashboards/vacancies/index.html.slim
h1 Listing vacancies

table
  thead
    tr
      th Title
      th Salary from
      th About
      th City
      th Remote
      th Relocate
      th
      th
      th

  tbody
    - @vacancies.each do |vacancy|
      tr
        td = vacancy.title
        td = vacancy.salary_from
        td = vacancy.about
        td = vacancy.city
        td = vacancy.remote
        td = vacancy.relocate
        td = link_to 'Show', vacancy
        td = link_to 'Edit', edit_vacancy_path(vacancy)
        td = link_to 'Destroy', vacancy, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Vacancy', new_vacancy_path

app/views/dashboards/vacancies/new.html.slim
h1 New vacancy

== render 'form'

app/views/dashboards/vacancies/show.html.slim
p#notice = notice

p
  strong Title:
  = @vacancy.title
p
  strong Salary from:
  = @vacancy.salary_from
p
  strong About:
  = @vacancy.about
p
  strong City:
  = @vacancy.city
p
  strong Remote:
  = @vacancy.remote
p
  strong Relocate:
  = @vacancy.relocate

= link_to 'Edit', edit_vacancy_path(@vacancy)
'|
= link_to 'Back', vacancies_path